package com.tamu222i.wsm.mapper;

import com.tamu222i.wsm.bean.Access;
import com.tamu222i.wsm.bean.AccessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int countByExample(AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int deleteByExample(AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int deleteByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int insert(Access record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int insertSelective(Access record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    List<Access> selectByExample(AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    Access selectByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int updateByExampleSelective(@Param("record") Access record, @Param("example") AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int updateByExample(@Param("record") Access record, @Param("example") AccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int updateByPrimaryKeySelective(Access record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESS
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    int updateByPrimaryKey(Access record);
}