package com.tamu222i.wsm.bean;

import java.util.Date;

public class Access {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCESS.IP
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCESS.ACCESS_TIME
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    private Date accessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCESS.IP
     *
     * @return the value of ACCESS.IP
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCESS.IP
     *
     * @param ip the value for ACCESS.IP
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCESS.ACCESS_TIME
     *
     * @return the value of ACCESS.ACCESS_TIME
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCESS.ACCESS_TIME
     *
     * @param accessTime the value for ACCESS.ACCESS_TIME
     *
     * @mbggenerated Mon Nov 21 13:18:21 JST 2016
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }
}